name: turbo_wookie
description: A sample Polymer application
dependencies:
  browser: any
  core_elements: any
  paper_elements: any
  polymer: ">=0.12.0+7"
transformers:
- polymer:
    entry_points: web/index.html
