name: turbo_wookie
description: A sample Polymer application
dependencies:
  browser: any
  polymer: ">= 0.9.2+2"
  custom_element: ">= 0.9.1+1"
transformers:
- polymer:
    entry_points: web/index.html
