# config.example.yaml
# an example configuration for Turbo Wookie's backend.
# 
# config.yaml is used in two ways, to generate an mpd.conf file
# and to set some server configuration variables (such as domain, and port, 
# and MPD's port).


#Don't use quotes in the config.yaml
mpd_command: mpd
server_port: 9000
server_domain: ""
mpd_http_domain: "localhost"
mpd_http_port: 8000
mpd_control_port: 6600

turbo_wookie_directory: "c:/users/rick/desktop/turbo-wookie/turbo-wookie"
mpd_subdirectory: "c:/users/rick/desktop/turbo-wookie/turbo-wookie/backend/mpd"

mpd_music_directory: "music"
mpd_playlist_directory: "playlists"
mpd_db_file: "database.db"
mpd_log_file: "log"
mpd_pid_file: "pid"
mpd_state_file: "state"
mpd_sticker_file: "sticker.sql"